---
- name: testing ignore_errors
  hosts: all
  tasks:
    - name: install pkg
      yum:
        name: httpd
        state: latest
    - name: copy index.html file
      copy:
        src: files/ind.html
        dest: /var/www/html/index.html
        ignore_errors: yes
    - name: message print
      debug:
        msg: "Done all Tasks"
  become: true
