--- # demo for loops playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks: 
          - name: add list of user in my nodes 
            user: name='{{item}}' state=present
            with_items: 
                    - sainath
                    - suresh
                    - akhilesh
                    - shubham
                    - sandeep 
